In [1]:
import numpy as np

In [2]:
np.__version__

'1.16.3'

In [3]:
help(np.fromfile)

Help on built-in function fromfile in module numpy:

fromfile(...)
    fromfile(file, dtype=float, count=-1, sep='')
    
    Construct an array from data in a text or binary file.
    
    A highly efficient way of reading binary data with a known data-type,
    as well as parsing simply formatted text files.  Data written using the
    `tofile` method can be read using this function.
    
    Parameters
    ----------
    file : file or str
        Open file object or filename.
    dtype : data-type
        Data type of the returned array.
        For binary files, it is used to determine the size and byte-order
        of the items in the file.
    count : int
        Number of items to read. ``-1`` means all items (i.e., the complete
        file).
    sep : str
        Separator between items if file is a text file.
        Empty ("") separator means the file should be treated as binary.
        Spaces (" ") in the separator match zero or more whitespace characters.
        A sepa

In [4]:
help(np.savetxt)

Help on function savetxt in module numpy:

savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='\n', header='', footer='', comments='# ', encoding=None)
    Save an array to a text file.
    
    Parameters
    ----------
    fname : filename or file handle
        If the filename ends in ``.gz``, the file is automatically saved in
        compressed gzip format.  `loadtxt` understands gzipped files
        transparently.
    X : 1D or 2D array_like
        Data to be saved to a text file.
    fmt : str or sequence of strs, optional
        A single format (%10.5f), a sequence of formats, or a
        multi-format string, e.g. 'Iteration %d -- %10.5f', in which
        case `delimiter` is ignored. For complex `X`, the legal options
        for `fmt` are:
    
        * a single specifier, `fmt='%.4e'`, resulting in numbers formatted
          like `' (%s+%sj)' % (fmt, fmt)`
        * a full string specifying every real and imaginary part, e.g.
          `' %.4e %+.4ej %.4e %+.4ej %.4

In [24]:
dataset = np.random.randint(1, 100, 10000)

In [25]:
dataset

array([28, 84, 57, ..., 25, 65, 39])

In [26]:
np.savetxt("sample1.txt", dataset, fmt="%d")

In [35]:
dataset = np.fromfile("sample1.txt", sep="\n", dtype=np.int64)

In [36]:
dataset

array([28, 84, 57, ..., 25, 65, 39], dtype=int64)

In [12]:
dataset[0]

1.3980432862761015e-76

In [32]:
2.96780801e-260

0

In [37]:
dataset.size

10000

In [38]:
dataset[0]

28

In [39]:
dataset[100]

97

In [40]:
dataset[0:100]

array([28, 84, 57, 52, 66,  4, 94, 19, 47, 54, 32, 16, 46, 80, 19, 22, 47,
       26,  9,  8, 40, 28, 76, 16, 76, 95, 87, 46, 15, 77,  2, 94, 69, 81,
       59, 14, 50, 54, 47, 39, 10, 40, 38, 69, 83, 93, 87, 96, 14, 56,  5,
       22, 66, 30, 85, 75, 70, 81, 42, 54, 53, 64, 80, 42,  2, 86, 29, 57,
       55, 16, 73, 96, 81, 17, 24, 12, 85, 78, 15, 98, 22, 37, 14, 23, 47,
       68, 22, 93, 76, 41, 58, 30, 68, 37, 96, 63, 97, 85, 82, 76],
      dtype=int64)

In [41]:
"this is test"[3:8]

's is '

In [42]:
"this is test"[-4:]

'test'

In [43]:
"this is test"[-6:-3]

's t'

In [44]:
"this is test"[12-6:12-3]

's t'

In [45]:
"this is test"[-6:-3:1]

's t'

In [46]:
"this is test"[2::2]

'i sts'

In [47]:
"this is test"[::-1]

'tset si siht'

In [48]:
"this is test"[::-2]

'te ish'

In [49]:
dataset[-100:]

array([42, 72, 28, 11, 38, 99, 88, 38, 20, 14, 57, 40, 20, 77, 54,  3, 17,
       17, 24, 88, 15, 87, 17, 67, 47, 81,  3, 48, 87, 27,  2, 98, 72, 33,
       57, 49, 63, 65, 86,  2, 32, 62, 61, 67, 72, 15, 31, 82, 81, 10, 54,
       94, 93, 52, 35, 64, 26, 28, 58, 41, 31,  2, 97, 69, 33,  1, 70, 38,
       67, 38, 32, 83,  2, 84, 89, 88, 75, 73, 92, 86, 10, 11, 55, 21, 59,
       89,  8, 88, 73, 90, 37, 74, 51, 51, 62, 45, 72, 25, 65, 39],
      dtype=int64)

In [50]:
dataset[dataset.size - 100:]

array([42, 72, 28, 11, 38, 99, 88, 38, 20, 14, 57, 40, 20, 77, 54,  3, 17,
       17, 24, 88, 15, 87, 17, 67, 47, 81,  3, 48, 87, 27,  2, 98, 72, 33,
       57, 49, 63, 65, 86,  2, 32, 62, 61, 67, 72, 15, 31, 82, 81, 10, 54,
       94, 93, 52, 35, 64, 26, 28, 58, 41, 31,  2, 97, 69, 33,  1, 70, 38,
       67, 38, 32, 83,  2, 84, 89, 88, 75, 73, 92, 86, 10, 11, 55, 21, 59,
       89,  8, 88, 73, 90, 37, 74, 51, 51, 62, 45, 72, 25, 65, 39],
      dtype=int64)

In [51]:
dataset < 10

array([False, False, False, ..., False, False, False])

In [54]:
dataset[(dataset < 10)[:100]]

IndexError: boolean index did not match indexed array along dimension 0; dimension is 10000 but corresponding boolean dimension is 100

In [55]:
dataset[dataset < 10]

array([4, 9, 8, 2, 5, 2, 9, 5, 1, 4, 9, 5, 1, 4, 6, 9, 4, 7, 5, 7, 4, 3,
       6, 4, 4, 7, 6, 8, 7, 1, 4, 8, 6, 9, 2, 1, 4, 7, 7, 7, 6, 3, 4, 1,
       2, 7, 5, 8, 5, 3, 5, 1, 9, 5, 4, 7, 8, 5, 9, 4, 7, 4, 6, 9, 8, 7,
       5, 3, 4, 1, 1, 3, 6, 1, 1, 8, 9, 4, 7, 4, 1, 9, 5, 1, 2, 1, 9, 9,
       7, 9, 5, 8, 3, 5, 7, 4, 9, 5, 7, 1, 8, 1, 4, 8, 3, 4, 7, 2, 4, 1,
       2, 1, 1, 3, 5, 4, 4, 7, 4, 5, 7, 9, 1, 4, 7, 9, 5, 2, 9, 6, 9, 5,
       2, 1, 6, 9, 3, 5, 8, 6, 3, 2, 7, 3, 2, 3, 9, 1, 7, 6, 8, 2, 5, 9,
       8, 3, 6, 7, 1, 4, 4, 4, 8, 7, 9, 7, 3, 1, 7, 1, 4, 7, 1, 1, 3, 9,
       7, 3, 4, 9, 8, 7, 9, 1, 8, 6, 6, 6, 6, 5, 4, 1, 9, 2, 6, 5, 9, 8,
       1, 3, 9, 1, 6, 9, 7, 7, 3, 1, 7, 4, 2, 6, 3, 7, 1, 1, 9, 9, 4, 1,
       2, 1, 5, 9, 6, 5, 8, 9, 5, 8, 4, 5, 5, 9, 3, 4, 2, 4, 4, 5, 9, 3,
       7, 9, 1, 7, 4, 8, 8, 3, 3, 8, 9, 3, 8, 3, 2, 1, 9, 7, 5, 7, 2, 1,
       4, 9, 8, 5, 2, 1, 9, 3, 6, 6, 7, 2, 9, 3, 1, 4, 9, 5, 7, 5, 6, 6,
       6, 6, 7, 7, 2, 6, 6, 4, 3, 5, 3, 7, 2, 1, 4,

In [56]:
dataset[dataset < 3 & dataset > 97]

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [57]:
dataset[(dataset < 3) & (dataset > 97)]

array([], dtype=int64)

In [58]:
dataset[(dataset < 3) | (dataset > 97)]

array([ 2,  2, 98,  1, 98,  1, 99, 99, 99,  1,  2,  1, 99,  1, 98,  2, 98,
        1, 99, 99, 98,  1, 99,  1,  1,  1,  1, 98,  1,  2, 99,  1, 99, 98,
       98, 98,  1,  1, 99,  2, 99,  1,  2,  1,  1, 99, 98, 99, 98, 99, 99,
        1, 99, 99,  2, 98,  2, 99,  1, 98, 99,  2, 98,  2, 99,  1,  2, 98,
        1, 98,  1,  1,  1,  1, 99, 99, 98, 98,  1,  1, 99, 99,  2,  1,  1,
       98, 98, 98,  1, 98, 98, 98, 99, 98,  2,  1, 98,  1,  1,  2, 99, 98,
        1, 98, 98, 98,  2,  1, 98,  2, 98,  1,  2,  1, 99,  2, 99, 98,  1,
       99, 99,  2,  1, 98, 98,  2,  2,  1, 99,  1, 98, 99,  1, 99,  2,  1,
       98, 99,  2,  1, 99,  2,  1, 99, 98,  2, 98, 99,  1,  1, 98, 98,  1,
        1, 98, 98,  2, 99, 99, 99, 99, 98,  2,  2, 98,  2, 98,  1, 98, 99,
        1,  2, 99,  2,  2,  2,  1,  1, 98,  1,  2, 98, 99, 99, 98,  1,  2,
        2,  2, 99,  1, 99, 99, 98, 98, 99, 98, 98, 99,  2, 99,  1,  2, 98,
       99, 99,  1, 98, 99, 99,  2,  2,  1,  2, 99,  2, 99,  1,  2, 99,  1,
        1,  1,  2,  2, 99

In [59]:
True and False

False

In [60]:
True or False

True

In [63]:
dset1 = dataset[dataset < 3]

In [64]:
dset1.size

223

In [65]:
dset1

array([2, 2, 1, 1, 1, 2, 1, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1, 2, 1,
       2, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 1, 1,
       2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 2,
       1, 2, 1, 2, 1, 2, 1, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 1, 1,
       1, 2, 1, 2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1, 1, 1, 2,
       2, 2, 1, 1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 2, 1, 1, 2, 1, 1, 2, 1, 1,
       2, 1, 2, 2, 2, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 2, 2, 2, 2, 1, 2, 1,
       1, 2, 2, 1, 1, 2, 2, 1, 2, 1, 2, 1, 1, 1, 2, 2, 1, 2, 1, 2, 2, 2,
       2, 2, 2, 1, 2, 1, 2, 1, 2, 2, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       1, 1, 2, 1, 2, 2, 1, 1, 2, 1, 1, 1, 2, 1, 2, 1, 2, 1, 2, 1, 2, 2,
       2, 1, 2], dtype=int64)

In [66]:
help(np.any)

Help on function any in module numpy:

any(a, axis=None, out=None, keepdims=<no value>)
    Test whether any array element along a given axis evaluates to True.
    
    Returns single boolean unless `axis` is not ``None``
    
    Parameters
    ----------
    a : array_like
        Input array or object that can be converted to an array.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a logical OR reduction is performed.
        The default (`axis` = `None`) is to perform a logical OR over all
        the dimensions of the input array. `axis` may be negative, in
        which case it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If this is a tuple of ints, a reduction is performed on multiple
        axes, instead of a single axis or all the axes as before.
    out : ndarray, optional
        Alternate output array in which to place the result.  It must have
        the same shape as the expected output an

In [67]:
np.any(dset1)

True

In [68]:
np.all(dset1)

True

In [72]:
dset1 < 2

array([False, False,  True,  True,  True, False,  True,  True, False,
        True,  True,  True,  True,  True,  True,  True, False,  True,
        True,  True, False,  True, False,  True,  True,  True, False,
       False,  True, False, False,  True, False,  True,  True,  True,
        True,  True,  True,  True, False,  True,  True,  True, False,
        True,  True,  True, False,  True, False,  True, False,  True,
       False,  True, False,  True, False,  True, False, False,  True,
        True,  True, False,  True, False,  True, False,  True, False,
        True,  True,  True,  True, False, False, False, False,  True,
        True, False, False, False, False,  True,  True,  True, False,
        True, False, False, False,  True, False,  True, False,  True,
       False, False,  True, False, False,  True, False,  True,  True,
        True, False, False, False,  True,  True, False,  True,  True,
       False,  True, False,  True, False, False, False,  True,  True,
       False,  True,

In [70]:
np.any(dset1 < 2)

True

In [71]:
np.all(dset1 < 2)

False

In [73]:
help(np.where)

Help on built-in function where in module numpy:

where(...)
    where(condition, [x, y])
    
    Return elements chosen from `x` or `y` depending on `condition`.
    
    .. note::
        When only `condition` is provided, this function is a shorthand for
        ``np.asarray(condition).nonzero()``. Using `nonzero` directly should be
        preferred, as it behaves correctly for subclasses. The rest of this
        documentation covers only the case where all three arguments are
        provided.
    
    Parameters
    ----------
    condition : array_like, bool
        Where True, yield `x`, otherwise yield `y`.
    x, y : array_like
        Values from which to choose. `x`, `y` and `condition` need to be
        broadcastable to some shape.
    
    Returns
    -------
    out : ndarray
        An array with elements from `x` where `condition` is True, and elements
        from `y` elsewhere.
    
    See Also
    --------
    choose
    nonzero : The function that is called whe

In [78]:
np.where(dset1 < 2, "One", "Two")

array(['Two', 'Two', 'One', 'One', 'One', 'Two', 'One', 'One', 'Two',
       'One', 'One', 'One', 'One', 'One', 'One', 'One', 'Two', 'One',
       'One', 'One', 'Two', 'One', 'Two', 'One', 'One', 'One', 'Two',
       'Two', 'One', 'Two', 'Two', 'One', 'Two', 'One', 'One', 'One',
       'One', 'One', 'One', 'One', 'Two', 'One', 'One', 'One', 'Two',
       'One', 'One', 'One', 'Two', 'One', 'Two', 'One', 'Two', 'One',
       'Two', 'One', 'Two', 'One', 'Two', 'One', 'Two', 'Two', 'One',
       'One', 'One', 'Two', 'One', 'Two', 'One', 'Two', 'One', 'Two',
       'One', 'One', 'One', 'One', 'Two', 'Two', 'Two', 'Two', 'One',
       'One', 'Two', 'Two', 'Two', 'Two', 'One', 'One', 'One', 'Two',
       'One', 'Two', 'Two', 'Two', 'One', 'Two', 'One', 'Two', 'One',
       'Two', 'Two', 'One', 'Two', 'Two', 'One', 'Two', 'One', 'One',
       'One', 'Two', 'Two', 'Two', 'One', 'One', 'Two', 'One', 'One',
       'Two', 'One', 'Two', 'One', 'Two', 'Two', 'Two', 'One', 'One',
       'Two', 'One',

In [79]:
np.where(dset1 < 2)

(array([  2,   3,   4,   6,   7,   9,  10,  11,  12,  13,  14,  15,  17,
         18,  19,  21,  23,  24,  25,  28,  31,  33,  34,  35,  36,  37,
         38,  39,  41,  42,  43,  45,  46,  47,  49,  51,  53,  55,  57,
         59,  62,  63,  64,  66,  68,  70,  72,  73,  74,  75,  80,  81,
         86,  87,  88,  90,  94,  96,  98, 101, 104, 106, 107, 108, 112,
        113, 115, 116, 118, 120, 124, 125, 127, 128, 130, 131, 133, 137,
        139, 142, 143, 145, 146, 151, 153, 154, 157, 158, 161, 163, 165,
        166, 167, 170, 172, 179, 181, 183, 186, 187, 188, 189, 190, 191,
        192, 193, 194, 195, 198, 199, 201, 204, 205, 207, 208, 209, 211,
        213, 215, 217, 221], dtype=int64),)

In [80]:
help(np.apply_along_axis)

Help on function apply_along_axis in module numpy:

apply_along_axis(func1d, axis, arr, *args, **kwargs)
    Apply a function to 1-D slices along the given axis.
    
    Execute `func1d(a, *args)` where `func1d` operates on 1-D arrays and `a`
    is a 1-D slice of `arr` along `axis`.
    
    This is equivalent to (but faster than) the following use of `ndindex` and
    `s_`, which sets each of ``ii``, ``jj``, and ``kk`` to a tuple of indices::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                f = func1d(arr[ii + s_[:,] + kk])
                Nj = f.shape
                for jj in ndindex(Nj):
                    out[ii + jj + kk] = f[jj]
    
    Equivalently, eliminating the inner loop, this can be expressed as::
    
        Ni, Nk = a.shape[:axis], a.shape[axis+1:]
        for ii in ndindex(Ni):
            for kk in ndindex(Nk):
                out[ii + s_[...,] + kk] = func1d(arr[ii + s_[:,] +

In [91]:
def mapp_nums(val):
    # print(val)
    if val == 1: return "One"
    elif val == 2: return "Two"
    elif val == 3: return "Three"
    else: return "Other"

In [82]:
dset2 = dataset[dataset < 5]

In [83]:
dset2[:10]

array([4, 2, 2, 1, 4, 1, 4, 4, 4, 3], dtype=int64)

https://docs.scipy.org/doc/numpy/reference/ufuncs.html

In [87]:
np.apply_along_axis(mapp_nums, 0, dset2)

[4 2 2 1 4 1 4 4 4 3 4 4 1 4 2 1 4 3 4 1 2 3 1 4 4 4 3 4 1 1 3 1 1 4 4 1 1
 2 1 3 4 1 1 4 3 4 2 4 1 2 1 1 3 4 4 4 1 4 2 2 1 3 3 2 3 2 3 1 2 3 1 4 4 4
 3 1 1 4 1 1 3 3 4 1 4 1 2 1 3 1 3 1 4 2 3 1 1 4 1 2 1 4 3 4 2 4 4 3 1 4 3
 3 3 3 2 1 2 1 4 2 1 3 2 3 1 4 2 4 3 3 2 1 4 1 4 3 4 1 4 2 3 1 3 4 3 3 2 1
 2 1 2 3 3 1 1 1 1 4 4 2 4 2 3 2 2 3 3 4 3 3 4 1 3 4 4 1 4 2 4 2 2 4 2 1 1
 1 2 4 3 4 4 1 3 2 3 2 4 2 1 2 1 4 2 1 3 2 2 1 2 3 2 4 1 3 2 1 4 1 1 3 2 2
 2 4 3 1 1 2 3 4 3 1 4 4 1 4 2 1 2 4 3 4 1 2 2 4 3 3 2 3 1 1 4 4 3 3 2 4 1
 4 1 2 1 1 2 3 3 4 1 2 2 3 3 3 4 2 4 3 3 1 2 1 2 2 1 1 2 1 4 1 4 2 2 2 2 1
 3 2 1 3 1 2 2 3 1 3 1 3 3 4 2 2 4 1 4 2 1 2 4 1 1 3 4 1 4 4 2 2 3 1 2 4 1
 2 2 2 2 2 2 1 2 1 2 1 2 2 3 1 1 4 1 3 3 1 1 1 3 1 1 4 4 3 1 3 4 3 1 2 2 4
 4 1 1 4 2 1 4 4 4 2 4 4 2 1 1 2 1 3 1 3 3 1 2 1 2 1 4 3 3 3 2 3 3 3 1 4 2
 3 4 3 1 4 3 3 2 2 2 1 2]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [88]:
help(np.vectorize)

Help on class vectorize in module numpy:

class vectorize(builtins.object)
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False, signature=None)
 |  
 |  vectorize(pyfunc, otypes=None, doc=None, excluded=None, cache=False,
 |            signature=None)
 |  
 |  Generalized function class.
 |  
 |  Define a vectorized function which takes a nested sequence of objects or
 |  numpy arrays as inputs and returns a single numpy array or a tuple of numpy
 |  arrays. The vectorized function evaluates `pyfunc` over successive tuples
 |  of the input arrays like the python map function, except it uses the
 |  broadcasting rules of numpy.
 |  
 |  The data type of the output of `vectorized` is determined by calling
 |  the function with the first element of the input.  This can be avoided
 |  by specifying the `otypes` argument.
 |  
 |  Parameters
 |  ----------
 |  pyfunc : callable
 |      A python function or method.
 |  otypes : str or list of dtypes, optional
 |      The 

In [94]:
# for item in dset2:
#     mapp_nums(item)

In [92]:
mapp = np.vectorize(mapp_nums)

In [93]:
mapp(dset2)

array(['Other', 'Two', 'Two', 'One', 'Other', 'One', 'Other', 'Other',
       'Other', 'Three', 'Other', 'Other', 'One', 'Other', 'Two', 'One',
       'Other', 'Three', 'Other', 'One', 'Two', 'Three', 'One', 'Other',
       'Other', 'Other', 'Three', 'Other', 'One', 'One', 'Three', 'One',
       'One', 'Other', 'Other', 'One', 'One', 'Two', 'One', 'Three',
       'Other', 'One', 'One', 'Other', 'Three', 'Other', 'Two', 'Other',
       'One', 'Two', 'One', 'One', 'Three', 'Other', 'Other', 'Other',
       'One', 'Other', 'Two', 'Two', 'One', 'Three', 'Three', 'Two',
       'Three', 'Two', 'Three', 'One', 'Two', 'Three', 'One', 'Other',
       'Other', 'Other', 'Three', 'One', 'One', 'Other', 'One', 'One',
       'Three', 'Three', 'Other', 'One', 'Other', 'One', 'Two', 'One',
       'Three', 'One', 'Three', 'One', 'Other', 'Two', 'Three', 'One',
       'One', 'Other', 'One', 'Two', 'One', 'Other', 'Three', 'Other',
       'Two', 'Other', 'Other', 'Three', 'One', 'Other', 'Three', 'Three'

In [95]:
def m1(arg):
    return arg

In [97]:
def hello(func):
    def wrapper(arg):
        return "Hello " + func(arg)
    return wrapper

In [99]:
m2 = hello(m1)

In [100]:
m2

<function __main__.hello.<locals>.wrapper(arg)>

In [101]:
m1("world")

'world'

In [102]:
m2("world")

'Hello world'

In [103]:
@hello
def m3(arg):
    return arg * 3

In [104]:
# m3 = hello(m3)

In [105]:
m3("world")

'Hello worldworldworld'